name: GitHub Pages
 
on:
  push:
    branches:
      - main  # æ›´æ”¹ä¸ºä½ çš„é»˜è®¤åˆ†æ”¯
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
 
      - name: Install and Build ğŸ”§ğŸ‘·
        run: |
          npm run preview  # æ›¿æ¢ä¸ºä½ çš„é¢„è§ˆå‘½ä»¤
      - name: Deploy ğŸš€
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # æ›¿æ¢ä¸ºä½ çš„é¢„è§ˆæ„å»ºç›®å½•